# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-03 09:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TotalRatings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_id', models.CharField(max_length=500)),
                ('ratings', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='UserRatings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_id', models.CharField(max_length=500)),
                ('username', models.CharField(max_length=100)),
                ('ratings', models.CharField(max_length=10)),
            ],
        ),
    ]
