# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-02-04 07:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userratings',
            name='cleanliness_ratings',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='userratings',
            name='hygiene_ratings',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
